### ISSUE TITLE
Plugin is still activated when we close the Longitudinal Profile Window

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-longitudinal-profile#11]
Hello @tdipisa , i've just installed the LongitudinalProfile on our portail-test and now i'm testing it.
Very cool :)

Mapstore versions are :
![image](https://user-images.githubusercontent.com/4659829/198636574-ecdde96a-e762-41b0-a520-99087bfc8f83.png)

I see that when I close the longitudinalProfile window, the plugin is still activated and I need to open and close another plugin to close this one.
See the demo bellow.
![bug1](https://user-images.githubusercontent.com/4659829/198635697-c0badfaa-f416-41e4-af01-8faa833653dd.gif)

**Comment by catmorales** [comment]
@landryb , @jusabatier , do you have the same behaviour ?

**Comment by landryb** [comment]
havent had time to test anything from 2022.02, sorry... might try in the coming weeks.

**Comment by catmorales** [comment]
@tdipisa any commentary ?

**Comment by tdipisa** [comment]
Hi @catmorales, I'm sorry for the late answer.

Yes, it is the expected behavior so that you can interact with the draw function also without having the side panel opened and to have the draw function active also enabling another tool. The draw option in the menu is a toggle button so that you can reopen the menu e click again on that option to disable it if you want. The draw tool is anyway disabled as soon as you activate another tool that interact with the map as usual.
